### ISSUE TITLE
Dependencies & setup.py

### ISSUE THREAD

**Issue by Sylphe88** [CaselIT/falcon-auth2#9]
Good job trying to bring together two libraries that haven't been maintained for a while, it looks good and I could transition from falcon-auth to falcon-auth2 easily!
However you should write a proper setup.py file, with basic information and dependencies. I had to look around and add authlib to my calling app's setup.py instead of delegating this part to falcon-auth2.

**Comment by CaselIT** [comment]
Hi,

Thanks! The transition falcon-auth -> falcon-auth2 should be quite easy. The main idea was to use similar concept but allow more configurability, since I often had to redefine thing that where hardcoded by falcon-auth.

I'm using [setup.cfg](https://github.com/CaselIT/falcon-auth2/blob/master/setup.cfg) to declare the dependencies.
It should work automatically with any recent version of pip.

From what I understand, setup.cfg is the suggested method to declare the setup dependencies. See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for additional details.

>  I had to look around and add authlib to my calling app's setup.py instead of delegating this part to falcon-auth2.

this is strange, from my end doing `pip install falcon-auth2` will install all the required libraries. Same thing happens when using setup.py to declare is as a dependency. Which version of pip are you using?

**Comment by Sylphe88** [comment]
Oops I browsed the Readme too fast and didn't see dependencies tagged with extra_requires... tagging [jwt] does install the authlib dependency as expected.
On a totally different note, it could be nice to have a small doc or article containing main painpoints to transition to your package, even if that was not too hard there were a few things to be cautious with (like the user_loader prototype taking an additional argument, similar but different keyword arguments for backend classes, missing utility functions for testing purposes...). But once again great job :)

**Comment by CaselIT** [comment]
Thanks for the suggestion, I'll try writing something.

> missing utility functions for testing purposes...

do you have some examples regarding what would be useful? From memory I did use utility function for tests in falcon-auth.
But I thing some could be added if there is an use case for them!
